#!/usr/bin/env bash

# Find the files to tested ( searches within folders )
exampleHeader=$(find / -xdev -name homework5.cpp)

# Copies the files into the Autograder's CWD 
cp $exampleHeader /autograder/source/homework5.cpp

cd /autograder/source

# Runs the student's make file ( if you're not using makefiles then place you compile command here )
make

python3 run_tests.py > /autograder/results/results.json
